sudo: false

language: java
jdk:
   - oraclejdk7

cache:
   directories:
     - '$HOME/.m2/repository'

install: /bin/true
script: 
  - echo $TRAVIS_PULL_REQUEST
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn -s ./travis-settings.xml -Prun-its -q -B -e install || mvn deploy -s ./travis-settings.xml -V -Prun-its -q -B -e' 
